var classes = [
    {
        "name": "src\\factory\\Frases",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "crear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "src\\FactoryClassInterface",
            "src\\frases\\Frases",
            "src\\frases\\FrasesValidas",
            "src\\frases\\ValoresValidos",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frase",
            "src\\frases\\Frases"
        ],
        "parents": [],
        "lcom": 1,
        "length": 142,
        "vocabulary": 39,
        "volume": 750.53,
        "difficulty": 3.3,
        "effort": 2474.71,
        "level": 0.3,
        "bugs": 0.25,
        "time": 137,
        "intelligentContent": 227.62,
        "number_operators": 20,
        "number_operands": 122,
        "number_operators_unique": 2,
        "number_operands_unique": 37,
        "cloc": 0,
        "loc": 27,
        "lloc": 27,
        "mi": 48.51,
        "mIwoC": 48.51,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 2,
        "totalSystemComplexity": 2,
        "package": "src\\factory\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "src\\factory\\PruebaScl90R",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "crear",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 1,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 1,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "src\\FactoryClassInterface",
            "src\\PruebaScl90R",
            "src\\Factory",
            "src\\molestia\\ValoresMolestia",
            "src\\molestia\\Molestia",
            "src\\PruebaScl90R"
        ],
        "parents": [],
        "lcom": 1,
        "length": 14,
        "vocabulary": 7,
        "volume": 39.3,
        "difficulty": 2,
        "effort": 78.61,
        "level": 0.5,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 19.65,
        "number_operators": 4,
        "number_operands": 10,
        "number_operators_unique": 2,
        "number_operands_unique": 5,
        "cloc": 0,
        "loc": 11,
        "lloc": 11,
        "mi": 65.98,
        "mIwoC": 65.98,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 1,
        "relativeDataComplexity": 1,
        "relativeSystemComplexity": 2,
        "totalStructuralComplexity": 1,
        "totalDataComplexity": 1,
        "totalSystemComplexity": 2,
        "package": "src\\factory\\",
        "pageRank": 0.03,
        "afferentCoupling": 0,
        "efferentCoupling": 5,
        "instability": 1,
        "violations": {}
    },
    {
        "name": "src\\frases\\Frase",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fraseTexto",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "fraseNumero",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "valorTexto",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "valorNumero",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setFrase",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "setValor",
                "role": null,
                "public": false,
                "private": true,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 7,
        "nbMethods": 3,
        "nbMethodsPrivate": 2,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 4,
        "nbMethodsSetters": 0,
        "wmc": 10,
        "ccn": 4,
        "ccnMethodMax": 3,
        "externals": [
            "src\\interfaces\\FraseInterface",
            "src\\frases\\FrasesValidas",
            "src\\frases\\ValoresValidos",
            "Exception",
            "Exception"
        ],
        "parents": [],
        "lcom": 1,
        "length": 58,
        "vocabulary": 11,
        "volume": 200.65,
        "difficulty": 7.69,
        "effort": 1542.47,
        "level": 0.13,
        "bugs": 0.07,
        "time": 86,
        "intelligentContent": 26.1,
        "number_operators": 17,
        "number_operands": 41,
        "number_operators_unique": 3,
        "number_operands_unique": 8,
        "cloc": 0,
        "loc": 53,
        "lloc": 53,
        "mi": 45.73,
        "mIwoC": 45.73,
        "commentWeight": 0,
        "kanDefect": 0.36,
        "relativeStructuralComplexity": 4,
        "relativeDataComplexity": 2.62,
        "relativeSystemComplexity": 6.62,
        "totalStructuralComplexity": 28,
        "totalDataComplexity": 18.33,
        "totalSystemComplexity": 46.33,
        "package": "src\\frases\\",
        "pageRank": 0.07,
        "afferentCoupling": 1,
        "efferentCoupling": 4,
        "instability": 0.8,
        "violations": {}
    },
    {
        "name": "src\\frases\\Frases",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase1",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase2",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase3",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase4",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase5",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase6",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase7",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase8",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase9",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase10",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase11",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase12",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase13",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase14",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase15",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase16",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase17",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 18,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 17,
        "nbMethodsSetters": 0,
        "wmc": 18,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface",
            "src\\interfaces\\FraseInterface"
        ],
        "parents": [],
        "lcom": 1,
        "length": 102,
        "vocabulary": 20,
        "volume": 440.84,
        "difficulty": 3.78,
        "effort": 1665.38,
        "level": 0.26,
        "bugs": 0.15,
        "time": 93,
        "intelligentContent": 116.69,
        "number_operators": 34,
        "number_operands": 68,
        "number_operators_unique": 2,
        "number_operands_unique": 18,
        "cloc": 0,
        "loc": 109,
        "lloc": 109,
        "mi": 36.91,
        "mIwoC": 36.91,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 17.94,
        "relativeSystemComplexity": 17.94,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 323,
        "totalSystemComplexity": 323,
        "package": "src\\frases\\",
        "pageRank": 0.16,
        "afferentCoupling": 3,
        "efferentCoupling": 1,
        "instability": 0.25,
        "violations": {}
    },
    {
        "name": "src\\frases\\FrasesValidas",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 34,
        "vocabulary": 34,
        "volume": 172.97,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.06,
        "time": 0,
        "intelligentContent": 345.95,
        "number_operators": 0,
        "number_operands": 34,
        "number_operators_unique": 0,
        "number_operands_unique": 34,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 68.95,
        "mIwoC": 68.95,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "src\\frases\\",
        "pageRank": 0.06,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "src\\frases\\ValoresValidos",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 10,
        "vocabulary": 10,
        "volume": 33.22,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 66.44,
        "number_operators": 0,
        "number_operands": 10,
        "number_operators_unique": 0,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 73.97,
        "mIwoC": 73.97,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "src\\frases\\",
        "pageRank": 0.06,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "src\\molestia\\Molestia",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "numero",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "texto",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 3,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 3,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 6,
        "ccn": 4,
        "ccnMethodMax": 4,
        "externals": [
            "src\\frases\\Frases",
            "src\\molestia\\ValoresMolestia"
        ],
        "parents": [],
        "lcom": 1,
        "length": 71,
        "vocabulary": 20,
        "volume": 306.86,
        "difficulty": 11.58,
        "effort": 3552.46,
        "level": 0.09,
        "bugs": 0.1,
        "time": 197,
        "intelligentContent": 26.51,
        "number_operators": 28,
        "number_operands": 43,
        "number_operators_unique": 7,
        "number_operands_unique": 13,
        "cloc": 0,
        "loc": 27,
        "lloc": 27,
        "mi": 50.82,
        "mIwoC": 50.82,
        "commentWeight": 0,
        "kanDefect": 0.45,
        "relativeStructuralComplexity": 361,
        "relativeDataComplexity": 0.13,
        "relativeSystemComplexity": 361.13,
        "totalStructuralComplexity": 1083,
        "totalDataComplexity": 0.4,
        "totalSystemComplexity": 1083.4,
        "package": "src\\molestia\\",
        "pageRank": 0.08,
        "afferentCoupling": 2,
        "efferentCoupling": 2,
        "instability": 0.5,
        "violations": {}
    },
    {
        "name": "src\\molestia\\ValoresMolestia",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [],
        "nbMethodsIncludingGettersSetters": 0,
        "nbMethods": 0,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 0,
        "nbMethodsGetter": 0,
        "nbMethodsSetters": 0,
        "wmc": 0,
        "ccn": 1,
        "ccnMethodMax": 0,
        "externals": [],
        "parents": [],
        "lcom": 0,
        "length": 10,
        "vocabulary": 10,
        "volume": 33.22,
        "difficulty": 0,
        "effort": 0,
        "level": 2,
        "bugs": 0.01,
        "time": 0,
        "intelligentContent": 66.44,
        "number_operators": 0,
        "number_operands": 10,
        "number_operators_unique": 0,
        "number_operands_unique": 10,
        "cloc": 0,
        "loc": 5,
        "lloc": 5,
        "mi": 73.97,
        "mIwoC": 73.97,
        "commentWeight": 0,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 0,
        "relativeSystemComplexity": 0,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 0,
        "totalSystemComplexity": 0,
        "package": "src\\molestia\\",
        "pageRank": 0.12,
        "afferentCoupling": 2,
        "efferentCoupling": 0,
        "instability": 0,
        "violations": {}
    },
    {
        "name": "src\\PruebaScl90R",
        "interface": false,
        "abstract": false,
        "final": false,
        "methods": [
            {
                "name": "__construct",
                "role": null,
                "public": true,
                "private": false,
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "frase",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            },
            {
                "name": "molestia",
                "role": "getter",
                "_type": "Hal\\Metric\\FunctionMetric"
            }
        ],
        "nbMethodsIncludingGettersSetters": 3,
        "nbMethods": 1,
        "nbMethodsPrivate": 0,
        "nbMethodsPublic": 1,
        "nbMethodsGetter": 2,
        "nbMethodsSetters": 0,
        "wmc": 3,
        "ccn": 1,
        "ccnMethodMax": 1,
        "externals": [
            "src\\frases\\Frases",
            "src\\molestia\\Molestia",
            "src\\frases\\Frases",
            "src\\molestia\\Molestia"
        ],
        "parents": [],
        "lcom": 1,
        "length": 12,
        "vocabulary": 5,
        "volume": 27.86,
        "difficulty": 2.67,
        "effort": 74.3,
        "level": 0.38,
        "bugs": 0.01,
        "time": 4,
        "intelligentContent": 10.45,
        "number_operators": 4,
        "number_operands": 8,
        "number_operators_unique": 2,
        "number_operands_unique": 3,
        "cloc": 23,
        "loc": 42,
        "lloc": 19,
        "mi": 107.42,
        "mIwoC": 61.85,
        "commentWeight": 45.56,
        "kanDefect": 0.15,
        "relativeStructuralComplexity": 0,
        "relativeDataComplexity": 2.67,
        "relativeSystemComplexity": 2.67,
        "totalStructuralComplexity": 0,
        "totalDataComplexity": 8,
        "totalSystemComplexity": 8,
        "package": "src\\",
        "pageRank": 0.05,
        "afferentCoupling": 1,
        "efferentCoupling": 2,
        "instability": 0.67,
        "violations": {}
    }
]